# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import da_dv_pb2 as da__dv__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in da_dv_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RecalculateAggregateStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecalculateAggregate = channel.unary_unary(
                '/RecalculateAggregate/RecalculateAggregate',
                request_serializer=da__dv__pb2.RecalculateRequest.SerializeToString,
                response_deserializer=da__dv__pb2.RecalculateResponse.FromString,
                _registered_method=True)


class RecalculateAggregateServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RecalculateAggregate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecalculateAggregateServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecalculateAggregate': grpc.unary_unary_rpc_method_handler(
                    servicer.RecalculateAggregate,
                    request_deserializer=da__dv__pb2.RecalculateRequest.FromString,
                    response_serializer=da__dv__pb2.RecalculateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RecalculateAggregate', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('RecalculateAggregate', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RecalculateAggregate(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RecalculateAggregate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RecalculateAggregate/RecalculateAggregate',
            da__dv__pb2.RecalculateRequest.SerializeToString,
            da__dv__pb2.RecalculateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RecalculateIndicatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecalculateIndicator = channel.unary_unary(
                '/RecalculateIndicator/RecalculateIndicator',
                request_serializer=da__dv__pb2.RecalculateRequest.SerializeToString,
                response_deserializer=da__dv__pb2.RecalculateResponse.FromString,
                _registered_method=True)


class RecalculateIndicatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RecalculateIndicator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecalculateIndicatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecalculateIndicator': grpc.unary_unary_rpc_method_handler(
                    servicer.RecalculateIndicator,
                    request_deserializer=da__dv__pb2.RecalculateRequest.FromString,
                    response_serializer=da__dv__pb2.RecalculateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RecalculateIndicator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('RecalculateIndicator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RecalculateIndicator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RecalculateIndicator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RecalculateIndicator/RecalculateIndicator',
            da__dv__pb2.RecalculateRequest.SerializeToString,
            da__dv__pb2.RecalculateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
