# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: da-dv.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'da-dv.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x64\x61-dv.proto\")\n\x12RecalculateRequest\x12\x13\n\x0bobject_name\x18\x01 \x01(\t\"%\n\x13RecalculateResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2Y\n\x14RecalculateAggregate\x12\x41\n\x14RecalculateAggregate\x12\x13.RecalculateRequest\x1a\x14.RecalculateResponse2Y\n\x14RecalculateIndicator\x12\x41\n\x14RecalculateIndicator\x12\x13.RecalculateRequest\x1a\x14.RecalculateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'da_dv_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECALCULATEREQUEST']._serialized_start=15
  _globals['_RECALCULATEREQUEST']._serialized_end=56
  _globals['_RECALCULATERESPONSE']._serialized_start=58
  _globals['_RECALCULATERESPONSE']._serialized_end=95
  _globals['_RECALCULATEAGGREGATE']._serialized_start=97
  _globals['_RECALCULATEAGGREGATE']._serialized_end=186
  _globals['_RECALCULATEINDICATOR']._serialized_start=188
  _globals['_RECALCULATEINDICATOR']._serialized_end=277
# @@protoc_insertion_point(module_scope)
